[package]
name = "submission"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1"
futures-lite = "1"
pin-project-lite = "0.2.9"

[target.'cfg(target_os = "linux")'.dependencies]
async-io = "1"
io-uring = { version = "=0.5.6", features = ["unstable"] }
libc = "0.2"

[features]
default = ["std"]
std = []
